import type {Metadata} from "next";
import "./globals.css";
import {ReactNode} from "react";
import {Toaster} from "@/shared/ui/shad-cn/sonner";
import {ThemeProvider} from "@/shared/lib/theme/theme-provider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

interface AppProps {
    children: ReactNode
}

export default async function RootLayout({children}: Readonly<AppProps>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`antialiased`}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            {children}
            <Toaster/>
        </ThemeProvider>
        </body>
        </html>
    )
}
