import type { Metadata } from 'next'
import './globals.css'
import { ReactNode, Suspense } from 'react'
import { Toaster } from '@/shared/ui/shad-cn/sonner'
import { ThemeProvider } from '@/shared/lib/theme/theme-provider'
import QueryProvider from '@/shared/lib/query-provider'
import ErrorProvider from '@/shared/ui/error-provider'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

interface AppProps {
  children: ReactNode
}

export default async function RootLayout({ children }: Readonly<AppProps>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <Toaster />
          <QueryProvider>
            <Suspense fallback={null}>
              <ErrorProvider>{children}</ErrorProvider>
            </Suspense>
            <ReactQueryDevtools initialIsOpen={false} />
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
